# Generated by Django 5.1.2 on 2024-10-27 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('hr', 'HR'), ('analyst', 'Analyst')], default='analyst', max_length=10)),
                ('department', models.CharField(choices=[('engineering', 'Engineering'), ('hr', 'HR'), ('sales', 'Sales')], default='sales', max_length=100)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
