# Generated by Django 5.1.2 on 2024-12-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_remove_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
